name: flutter_web
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.14.0
  firebase_auth_web: ^5.9.8 
  cloud_firestore: ^4.14.0
  get_it: ^7.2.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  uuid: ^4.2.2
  dartz: ^0.10.1
  faker: ^2.1.0
  intl: ^0.19.0
  flag: ^7.0.0
  url_strategy: ^0.2.0
  routemaster: ^1.0.1
  responsive_framework: ^0.2.0
  url_launcher: ^6.2.5
  scrollable_positioned_list: ^0.3.8



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  
  # Test dependencies
  mocktail: ^1.0.3
  bloc_test: ^9.1.5
  fake_cloud_firestore: ^2.4.1+1
  firebase_auth_mocks: ^0.13.0
  build_runner: ^2.4.7
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/product_sans_regular.ttf
        - asset: assets/fonts/product_sans_bold.ttf
          weight: 700
        - asset: assets/fonts/product_sans_italic.ttf
          style: italic
  #
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
